string = "Hello, World!"
name = "Jimmy"
print(string)  # Output: Hello, World!
print(string.lower())  # Output: hello, world!
print(string.upper())  # Output: HELLO, WORLD!
print(string.capitalize())  # Output: Hello, world!
print(string.title())  # Output: Hello, World!
print(string.swapcase())  # Output: hELLO, wORLD!
print(string.count("o"))  # Output: 2
print(string.find("World"))  # Output: 7
print(f"Hello, {name}!")  # Output: Hello, Jimmy!
print(string.index("e"))  # Output: 1``